ipfs/ipfs-desktop

- index.js
This seems to be needed both for mainWindow and the tray.
> make gc not eat the tray

- index.js
Closes https://github.com/ipfs/electron-app/issues/4
> Fix OSX Tray icon

- package.json
Otherwise assets will not build correctly. Maybe there should be
a check somewhere, as it took me a while to figure out what was wrong
> make sure `npm start` runs `./build.sh`

- build.sh
> Use local browserify

- app/init.js
- index.js
- package.json
This at least stops #53 from crashing the machine, though it does not solve the underlying issue.
> feat: Ensure only one instance can run at a time.

- src/index.js
- src/js/screens/menu/node-info.js
- src/styles/panel.less
> feat: add close option

- src/utils/stats-poller.js
> fix: start polling stats on window show to avoid delay

- src/utils/stats-poller.js
> refactor: improve and simplify poller

- src/index.js
Hopefully fixes the Copy/Paste issue on macOS.
> fix: macOS copy/paste

- .compilerc
- package.json
- src/config.js
- src/controls/main/index.js
- src/controls/main/stats.js
- src/index.js
- src/screens/menubar.js
> Improve StatsPoller performance

- src/config.js
- src/index.js
- src/panes/Settings.js
- src/utils/key-value-store.js
> feat: default profile as dhtclient

- package.json
- src/index.js
> feat: connect already running daemon

- README.md
This PR closes #630 by adding a  note for Debian and Ubuntu users about  `apt install`.
> Add note for Debian and Ubuntu users

- package.json
- src/controls/main/gc.js
- src/controls/main/index.js
- src/panes/Settings.js
Adds a button on settings to run **garbage collector**.
I'm thinking of making some simple system of noticication to let the user know when something works and doesn't work.
Closes #635
> feat: garbage collector button on settings

- package.json
> feat: update web ui to include desktop settings

- package-lock.json
- package.json
- src/index.js
This is the bare minimum code needed to set up auto updating. It is supposed to automatically detect the repository URL through `package.json`. It looks on the releases for the binaries and `latest.yaml` files produced by `electron-builder`.
We can listen to events and modify some behavior if needed.
License: MIT
> feat: add auto updater

- package.json
Check [release v2.3.0](https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.3.0) to see the latest changes.
> feat: update to Web UI v2.3.0

- package-lock.json
- package.json
> chore: update to electron 4

- src/locales/de.json
> German (de.json)

- src/lib/menubar/app/utils/screenshot.js
> fix: black screenshot

- package.json
Check [release v2.3.2](https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.3.2) to see latest changes.
> feat: update to Web UI v2.3.2

- package.json
This fixes a regression for adding files/folders introduced in the previous release.
Check the [release notes](https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.3.3) for more info.
> chore: update to Web UI v2.3.3

- src/lib/take-screenshot.js
- src/locales/en.json
Extract notifications text into i18n files.
License: MIT
> feat: extract notifications text

- src/lib/menubar/index.js
> feat: move quit button to the end to match other apps

- src/lib/download-hash.js
- src/lib/second-instance.js
- src/lib/take-screenshot.js
- src/locales/en.json
- src/utils/errors.js
- src/utils/index.js
- src/utils/notify.js
Improve descriptions and add thumbnails.
License: MIT
> feat: improve notifications

- src/lib/add-to-ipfs.js
- src/lib/auto-launch.js
- src/lib/download-hash.js
- src/lib/ipfs-stats.js
- src/lib/menubar/index.js
- src/lib/register-daemon.js
- src/lib/take-screenshot.js
- src/lib/webui/index.js
- src/utils/daemon.js
- src/utils/logger.js
Improves logs messages by telling the source and more info about what's happening.
> refactor: improve log messages

- src/lib/menubar/index.js
- src/locales/en.json
> feat: add config file to right-click menu

- README.md
Add to the docs the answer for the questions on #817.
> docs: add some FAQs

- src/lib/add-to-ipfs.js
- src/lib/index.js
- src/lib/menubar/index.js
- src/lib/webui/index.js
> feat: drop files in the tray (macOS)

- src/lib/menubar/index.js
- src/lib/webui/index.js
> feat: listen to crashed and unresponsive events on windows

- src/lib/auto-updater.js
- src/lib/index.js
- src/lib/menubar/index.js
- src/locales/en.json
Closes #839.
Added an option to the context menu to check for updates just above 'Quit'. Also, we now check for updates every hour.
License: MIT
> feat: check for updates cron and ctx menu

- package.json
Check the [release notes](https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.4.0) for more info!
> chore: update to Web UI v2.4.0

- src/lib/take-screenshot.js
> fix: date error while taking screenshot

- .tx/config
- electron-builder.yml
- package.json
> feat: move build conf to separate file and add deb

- LICENSE
- package.json
> chore: update metadata

- src/lib/menubar/index.js
> fix: only one menu at a time

- package.json
Analytics are now **opt-in**. Check the [release notes](https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.4.1)!
> chore: update to Web UI v2.4.1

- src/lib/register-daemon.js
- src/lib/tray.js
Improves IPFSD status handling.
> feat: better statuses

- src/lib/webui/preload.js
Ref.: https://github.com/ipfs-shipyard/ipfs-webui/issues/992
> feat: add countly key

- src/utils/quit-and-install.js
Hopefully this fixes the issue with auto-update. I rely on the events, although they're not my favourite thing.
> fix: wait for ipfs to shutdown

- README.md
Add a download section at the top, and add info on package mangers to the install section.
> docs: make downloads the main thing

- README.md
Badges that help us figure out if folks are downloading the latest releases. We need to remember to update it as part of the release process.
> docs: add download count badges [ci skip]

- src/late/tray.js
> fix: hide restart when not running

- .travis.yml
- package-lock.json
- package.json
> chore: update electron

- assets/locales/ca.json
- assets/locales/cs.json
- assets/locales/da.json
- assets/locales/de.json
- assets/locales/eo.json
- assets/locales/es.json
- assets/locales/fr.json
- assets/locales/hr.json
- assets/locales/hu.json
- assets/locales/it.json
- assets/locales/ja.json
- assets/locales/ko-KR.json
- assets/locales/nl.json
- assets/locales/no.json
- assets/locales/pl.json
- assets/locales/pt-BR.json
- assets/locales/pt.json
- assets/locales/ru.json
- assets/locales/sk.json
- assets/locales/sl.json
- assets/locales/sr.json
- assets/locales/sv.json
- assets/locales/uk.json
- assets/locales/zh-CN.json
- assets/locales/zh-HK.json
- assets/locales/zh-TW.json
> feat: update i18n locales

- package.json
> feat: update to web ui 2.4.5

- src/late/webui/preload.js
> feat: provide app version

- package-lock.json
- package.json
- src/index.js
Please see https://github.com/sindresorhus/fix-path.
License: MIT
> fix: macOS path

- src/late/register-daemon.js
> fix: don't restart when stopped

- src/late/ipfs-on-path/index.js
- src/late/ipfs-on-path/scripts/bin-win/ipfs.cmd
> fix: escape spaces path windows

- src/late/register-daemon.js
Fixes the stop daemon function. Forgot to change to the async API here.
License: MIT
> fix: stopping daemon with new ipfsd

- assets/locales/en.json
- src/late/download-hash.js
> feat: improve hash clipboard message

- src/late/download-hash.js
Downloading "hash" now supports any IPFS paths (from /ipfs/... /ipns/... to just CIDs).
Also, fixed a bug where if there were multiple directories inside it wouldn't work.
License: MIT
> feat: support more download paths

- src/late/tray.js
- src/utils/setup-global-shortcut.js
> fix: only show accelerators on macOS

- src/dialogs/dialog.js
- src/late/download-hash.js
- src/late/ipfs-on-path/index.js
- src/late/take-screenshot.js
- src/late/tray.js
- src/utils/consts.js
- src/utils/index.js
- src/utils/setup-global-shortcut.js
> refactor: IS_OS const

- src/late/auto-launch.js
- src/late/download-hash.js
- src/late/ipfs-on-path/index.js
- src/late/npm-on-ipfs/index.js
- src/late/take-screenshot.js
> refactor: consistency across config keys consts

- src/early/protocol-handlers.js
Open ipns://, ipfs:// and dweb:/ links with local gateway when available to promote the usage of the local gateway and all of the benefits that come with it.
License: MIT
> feat: open with local gateway

- src/dialogs/dialog.js
- src/dock.js
- src/webui/index.js
> fix: don't hide dock when there are active windows

- src/npm-on-ipfs/package.js
> fix: import IS_WIN from consts

- src/ipfs-on-path/scripts/bin-win/ipfs.cmd
- src/ipfs-on-path/scripts/ipfs.sh
> fix: ipfs path on script

- package.json
Release notes of [v2.5.0](https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.5.0).
> chore: update to Web UI v2.5.0

- assets/locales/en.json
- package-lock.json
- package.json
- src/cohost.js
- src/index.js
- src/tray.js
> feat: co-host websites

- src/tray.js
> feat: cmd+r for restart on macOS

- src/auto-updater/index.js
> fix: notify import

- src/common/consts.js
- src/tray.js
> fix: use go-ipfs version from package.json section

- package.json
See https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.5.1.
> feat: web ui 2.5.1

- package.json
> feat: webui 2.5.2

- src/add-to-ipfs.js
- src/auto-launch.js
- src/auto-updater/index.js
- src/common/consts.js
- src/common/logger.js
- src/daemon/daemon.js
- src/daemon/index.js
- src/download-hash.js
- src/index.js
- src/npm-on-ipfs/package.js
- src/take-screenshot.js
- src/webui/index.js
- src/webui/preload.js
Pulled this code out of #1068 to improve logging a bit and simplify the Analytics PR! Mostly, I'm adding more information to the logging and make sure it's consistent across the entire code.
> refactor: improve logging

- electron-builder.yml
> chore: add freebsd

- src/daemon/index.js
> fix: call function on err.toString

- .travis.yml
- electron-builder.yml
> chore: publish snap to snap store

- electron-builder.yml
> chore: snap stable channel

- src/npm-on-ipfs/index.js
`ipfs-npm` was being install by default if the user had node installed for reasons that transcend my mere existence. I don't know why I wrote it that way, but certainly I shouldn't. This fixes that and closes #1194.
License: MIT
> fix: do not install npm-ipfs by default

- src/auto-launch.js
> fix: auto launch on login on linux

- package.json
[Release notes](https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.7.1).
> feat: web ui 2.7.1

- README.md
https://github.com/ipfs-shipyard/ipfs-desktop/pull/1351#issuecomment-589529319
> fix: Transifex link in readme

- package-lock.json
- package.json
- src/auto-launch.js
> fix: remove old auto launch method

- src/webui/screenshot.js
Closes #1417. The API is now async!
License: MIT
> fix: screenshot taking

- assets/locales/en.json
- src/dialogs/select-directory.js
> fix: translate 'Select Directory'

- README.md
> docs: clarify protocol usage

- src/auto-updater/index.js
> fix: disable updates in development

- package.json
> feat: go-ipfs 0.5.0-rc4

- package.json
Switching from RC4 to final release build.
cc #1415 https://github.com/ipfs/go-ipfs/issues/7109
> feat: go-ipfs 0.5.0

- README.md
adding scoop to the "favorite package manager" list
> docs: add scoop install instruction

- src/webui/preload.js
Removes code that's addressed by https://github.com/ipfs-shipyard/ipfs-webui/pull/1628
> chore: remove unused code

- package.json
https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.11.3
This aims to unblock #1661 by including fix from  https://github.com/ipfs-shipyard/ipfs-webui/pull/1660
> chore: webui v2.11.3

- README.md
Use `brew install --cask` now.
> Brew cask has been deprecated

- src/daemon/config.js
This should mitigate problem described in https://github.com/ipfs-shipyard/ipfs-desktop/issues/1723#issuecomment-766165256 and help with first point of #1749
> fix: timeout during checkIfAddrIsDaemon

- src/add-to-ipfs.js
- src/webui/index.js
> fix(mac): force-refresh file list after import

- .github/workflows/ci.yml
@olizilla any concerns regarding switching to v2?
> chore: switch actions to v2

- .github/workflows/snapcraft.yml
This PR makes snapcraft publishing more flexible + runs test on this PR.
> fix: flexible snapcraft publishing

- README.md
I was lead from https://github.com/ipfs/ipfs-desktop/issues/691.
> readme: add winget instructions

- src/add-to-ipfs.js
> fix: dont pin when adding to mfs

- package.json
This includes a bugfix release of webui.
Release notes: https://github.com/ipfs/ipfs-webui/releases/tag/v2.12.4
> fix: ipfs-webui  v2.12.4

- package.json
Release Notes: https://github.com/ipfs/ipfs-webui/releases/tag/v2.13.0
Closes  #1801
> feat: ipfs-webui v2.13.0

- .github/workflows/ci.yml
- package-lock.json
- package.json
Ref. https://github.com/ipfs/go-ipfs/issues/8343
> feat: go-ipfs 0.11.0

- package.json
Release Notes: https://github.com/ipfs/ipfs-webui/releases/tag/v2.14.0 (mostly bugfixes)
> chore: ipfs-webui v2.14.0

- src/daemon/config.js
- test/e2e/launch.e2e.test.js
> fix: increase free port lookup range

- CHANGELOG.md
- README.md
> docs: v0.20.6

- src/auto-launch.js
- src/automatic-gc.js
- src/common/config-keys.js
- src/enable-namesys-pubsub.js
- src/enable-pubsub.js
- src/take-screenshot.js
- src/tray.js
- src/webui/index.js
> chore(maintenance): move config keys to separate file

- src/add-to-ipfs.js
- src/daemon/index.js
- src/index.js
- src/move-repository-location.js
- src/take-screenshot.js
- src/webui/index.js
Uses the constants created in #2126 for the metric keys, avoiding typos and wrong keys. Partially fixes #2191.
License: MIT
> fix: use constants for withAnalytics keys

- package.json
https://github.com/ipfs/ipfs-webui/releases/tag/v2.18.0
> chore(deps): webui v2.18.0

- package.json
feat: ipfs-webui v2.18.1
https://github.com/ipfs/ipfs-webui/releases/tag/v2.18.1
> feat: ipfs-webui v2.18.1

- README.md
@SgtPooki seems you forgot to do step 7 from https://github.com/ipfs/ipfs-desktop/blob/main/DEVELOPER-NOTES.md#main-release-process  – perhaps it could be automated?
> chore(readme): 0.24.0

- CHANGELOG.md
- README.md
Also, updated the cask: https://github.com/Homebrew/homebrew-cask/pull/135584
> chore(readme): 0.24.0 -> 0.24.1

- package-lock.json
- package.json
Part of https://github.com/ipfs/kubo/issues/9319
https://github.com/ipfs/kubo/blob/master/docs/changelogs/v0.17.md
> feat: kubo v0.17.0

- CHANGELOG.md
- README.md
https://github.com/ipfs/ipfs-desktop/releases/tag/v0.26.0
> chore(docs): v0.26.0

- package-lock.json
- package.json
This PR updates Kubo to v0.18.1
> Update Kubo: v0.18.1

- package-lock.json
- package.json
This PR updates Kubo to v0.19.0
> Update Kubo: v0.19.0

- package-lock.json
- package.json
This PR updates Kubo to v0.19.1
> Update Kubo: v0.19.1

- package.json
see https://github.com/ipfs/ipfs-webui/releases/tag/v3.0.0
> feat: webui@3.0.0

- package-lock.json
- package.json
This PR updates Kubo to v0.19.2
> Update Kubo: v0.19.2

- package-lock.json
- package.json
This PR updates Kubo to v0.20.0
> Update Kubo: v0.20.0

- package.json
see https://github.com/ipfs/ipfs-webui/releases/tag/v4.0.2
> feat: webui@4.0.2

- package-lock.json
- package.json
This PR updates Kubo to v0.21.0
> Update Kubo: v0.21.0

- package.json
Update webui https://github.com/ipfs/ipfs-webui/releases/tag/v4.1.1
> deps: webui v4.1.1

- DEVELOPER-NOTES.md
- pkgs/macos/notarize-build.js
- pkgs/macos/notarize-cli.js
fixes https://github.com/ipfs/ipfs-desktop/issues/2623
> fix(apple-notarize): use notarytool and teamId

- .github/workflows/ci.yml
- package.json
- chore: fix release-please CI
- chore: prevent release-gh script plugin not found
> fix: release-please release creation

- package.json
https://github.com/ipfs/ipfs-webui/releases/tag/v4.2.0
> deps: webui v4.2.0

- package-lock.json
- package.json
This PR updates Kubo to v0.26.0
> feat: kubo v0.26.0

- package-lock.json
- package.json
This PR updates Kubo to v0.28.0
> Update Kubo: v0.28.0

- .github/workflows/ci.yml
Context: https://github.com/ipfs/ipfs-desktop/issues/2809#issuecomment-2115259649
Closes #2809
> fix: downgrade to macos-13 for intel-compat build

- package.json
https://github.com/ipfs/ipfs-webui/releases/tag/v4.3.0
> feat: webui v4.3.0

- package-lock.json
- package.json
> feat: kubo 0.30.0

- package.json
- https://github.com/ipfs/ipfs-webui/releases/tag/v4.3.1
- https://github.com/ipfs/ipfs-webui/releases/tag/v4.3.2
> feat: use ipfs-webui@4.3.2

- package.json
https://github.com/ipfs/ipfs-webui/releases/tag/v4.3.3
> feat: ipfs-webui v4.3.3

- package-lock.json
- package.json
- src/dialogs/errors.js
https://github.com/ipfs/kubo/releases/tag/v0.32.1
> chore: kubo 0.32 + electron 33.2

- package.json
https://github.com/ipfs/ipfs-webui/releases/tag/v4.4.1
> fix: ipfs-webui v4.4.1

- package.json
https://github.com/ipfs/ipfs-webui/releases/tag/v4.4.2
> fix: ipfs-webui v4.4.2

- package.json
https://github.com/ipfs/ipfs-webui/releases/tag/v4.6.0
> feat: ipfs-webui v4.6 with CAR import

- package.json
https://github.com/ipfs/ipfs-webui/releases/tag/v4.7.0
> feat: ipfs-webui v4.7

- package-lock.json
- package.json
- https://github.com/ipfs/kubo/issues/10816
- https://github.com/ipfs/kubo/blob/master/docs/changelogs/v0.36.md
> feat: kubo 0.36

- package.json
https://github.com/ipfs/ipfs-webui/releases/tag/v4.8.0
> feat: ipfs-webui v4.8.0

- package-lock.json
- package.json
- https://github.com/ipfs/kubo/issues/10867
> feat: kubo 0.37
