ipfs/ipfs-desktop

README.md

As discussed in an issue stemming from my confusing of how the app was run (https://github.com/ipfs/electron-app/issues/39#issuecomment-139782596) I added a line explaining that this is a menu bar app. I guess down the road the README could explain any differences that other operating systems handle menu bar / tray applications.

Add line to README explaining that this is a menu bar app

---

README.md
app/init.js
app/js/alt-menubar.jsx
app/js/components/files.jsx
app/js/components/open-links.jsx
app/js/components/quit.jsx
app/js/components/settings.jsx
app/js/components/stats.jsx
app/js/components/status.jsx
app/js/components/version.jsx
app/js/help.js
app/js/menubar-toggle.jsx
app/js/menubar.jsx
app/js/settings.jsx
app/views/menubar.html
build.sh
package.json

* Merge latest `master`
* Enable linting and fix lint issues
* Split menubar into multiple components
* No more react warnings in the menubar

First round of improvements

---

package.json

> never include the path to node_modules/.bin/
> Just trust the PATH environ.
- https://twitter.com/izs/status/657976995326726144
- https://twitter.com/izs/status/657977615228104704
Just cleaning up the package.json scripts a little bit, and added a coupe lifecycle steps where it made sense.

Remove package.json hard paths and add lifecycle stages

---

README.md

You need to have SSH key that is assigned to GH account to be able to clone using SSH.

Change example clone to be HTTPS based

---

README.md

In #517 I ran into a barrier in building station. With @VictorBjelkholm's guidance, I was able to install the dependencies and get up-and-running. Adding this change to the README would help others get going quicker.

Add further requirements to build on macOS

---

CONTRIBUTING.md

In #519, the CONTRIBUTING file suggests adhering to a conventions file when submitting a PR. The link to this file is broken in the Station CONTRIBUTING.md. This PR updates the link. 
As the originally linked page no longer exists, I am unsure if this was the intended link, but based on the now-changed project structure, the new URI is my best guess as to what was intended.

Update conventions link in CONTRIBUTING

---

.gitignore
package.json
src/js/screens/menu.js
src/js/screens/menu/node-info.js
src/utils/stats-poller.js

feat: add bandwidth stats

---

postinst.sh

Changes the permission of the script, makes sure we exit directly when something fails and debug output for when things are OK.

Fix permissions + exit on error

---

appveyor.yml

Enables AppVeyor. It:
1. Runs `lint` to check if the code is syntactically OK.
2. Runs `make` to check if the code is buildable on Windows 64 bits.

chore: add appveyor

---

package.json
src/config.js
src/controls/main/toggle-sticky.js
src/index.js

I'm building a small module called 'electron-menubar' which is based on 'menubar', but with its code cleaned and a simpler API and a bunch of bugs fixed (like the correct position on Linux distributions).

[WIP] refactor: use electron-menubar instead of menubar

---

src/controls/main/download-hash.js
src/controls/main/index.js
src/controls/utils.js
src/js/screens/settings.js

With this PR you can now activate the `CTRL/CMD`+`ALT`+`D`  shortcut to download the hash you've copied into your clipboard.

feat: download copied hash

---

README.md
package.json
src/config.js
src/controls/main/download-hash.js
src/controls/main/index.js
src/controls/main/pinned-files.js
src/controls/utils.js
src/js/components/logic/new-pinned-hash.js
src/js/components/view/checkbox-block.js
src/js/components/view/file-block.js
src/js/components/view/header.js
src/js/components/view/info-block.js
src/js/components/view/pinned-hash.js
src/js/panes/files.js
src/js/panes/pinned.js
src/js/panes/settings.js
src/js/screens/menu.js
src/styles/app.less
src/styles/components/checkbox-block.less
src/styles/components/info-block.less
src/styles/components/new-pinned-hash.less
src/styles/components/pane.less
src/utils/file-history.js
src/utils/file-store.js
src/utils/key-value-store.js
src/utils/pinned-files.js
src/utils/stats-poller.js

Ref.: #518 
[![https://gyazo.com/cc95c17262a58052d43230cb756f5c09](https://i.gyazo.com/cc95c17262a58052d43230cb756f5c09.gif)](https://gyazo.com/cc95c17262a58052d43230cb756f5c09)
[![https://gyazo.com/7e1d694d77174bd6c3493812c11318ab](https://i.gyazo.com/7e1d694d77174bd6c3493812c11318ab.gif)](https://gyazo.com/7e1d694d77174bd6c3493812c11318ab)
[![https://gyazo.com/72e7b03963fa2eec270b2516f4f84437](https://i.gyazo.com/72e7b03963fa2eec270b2516f4f84437.gif)](https://gyazo.com/72e7b03963fa2eec270b2516f4f84437)

feat: pinning

---

README.md

FOSSA badge doesn't actually show which license is being used.

Add MIT license to README

---

package.json
src/config.js
src/controls/main/auto-launch.js
src/controls/main/download-hash.js
src/controls/main/open-webui.js
src/controls/main/pinned-files.js
src/controls/main/settings.js
src/controls/main/take-screenshot.js
src/controls/utils.js
src/index.js
src/utils/stats-poller.js

**Edit:** just noticed that the daemon is always exiting with error on Windows.

fixes: use debug, correctly open settings and offline stats

---

README.md

Makes the readme a little calmer. 
- Add a static screenshot to retain the visual interest without the animation.
- Pull the gifs lower down, and make them a **Usage** section. 
- Drop the settings gif and the light theme gif.
- Re-order the content as per standard-readme.
- Focus the install section on users. Clarify that installing from source is there if you need it. Simplify the content.
- Group the dev info under a **Developer Guide** so users get a hint that it's ok to ignore it.

Enhance your calm, README.

---

src/controls/main/index.js
src/controls/main/open-url.js
src/js/components/view/file-block.js
src/styles/components/info-block.less

Closes #583.
This removes the option to copy a file's hash to the clipboard and instead it opens the link in your default browser.

feat: open on click

---

package.json
src/controls/main/stats.js
src/screens/menubar.js

fix: refresh pins and stats at better rates

---

src/config.js
src/controls/utils/upload-files.js
src/panes/Files.js

fix: upload directory with subdirectories [WIP]

---

src/utils/daemon.js

AFAIK IPFS Desktop does not need this header.
See also:
- Potential problem with  `Access-Control-Allow-Credentials`: https://github.com/ipfs/go-ipfs/issues/5745
- HTTP Headers Cleanup: https://github.com/ipfs/in-web-browsers/issues/132

fix: do not add CORS Credentials header

---

src/utils/daemon.js

Adds flag `--migrate=true` to migrate the repo automatically to the newest version.
License: MIT

feat: automatically migrate repository (fixes #687)

---

src/index.js

If an error occurs while Electron is getting ready, we just show up a dialog telling that. There isn't much we can do. On the other hand, if the error happens during the execution of IPFS Desktop itself, we will have this error message:
The first option clearly opens the logs directory. The second option opens an URL to an issue pre-filled with the details of the error, like this:
This was something we didn't have in the last version, but we need to improve a lot: error handling! This will catch any major errors that might not be caught in other parts of the app.
License: MIT

feat: handle errors better

---

src/utils/daemon.js

`Access-Control-Allow-Method` was missing `s` :)

fix: a typo in CORS header name

---

src/index.js
src/utils/daemon.js

Previously we were cleaning up the `api` and `repo.lock` files because the shutdown on Windows was not working correctly on the IPFS daemon. It seems the issue was already resolved (see https://github.com/ipfs/go-ipfs/issues/3061).
This PR removes that code and this should also fix #689 and fix #688.
@lidel can you check this out, please?

fix: do not cleanup api and repo.lock files

---

src/hooks/webui/index.js

This should fix the issue where the Web UI language wouldn't match menubar's. @lidel could you take a look to see if it works on your end?
License: MIT

fix: Web UI language matches menubar

---

src/utils/daemon.js

This fixes an issue when the `API.HTTPHeaders` key is empty on the IFPS configuration. When that happens, we just assume the array of origins is an empty array.
fixes #676.
/cc @NatoBoram
License: MIT

fix: no error when API.HTTPHeaders is empty

---

package-lock.json
package.json

TL;DR  A package (flatmap-stream) got updated to include some dodgy code relating to crypto currency hijacking. This got included in event-stream which was pulled in by npm-run-all.
Context: https://github.com/dominictarr/event-stream/issues/116

Remove malicious package from transitive dependencies

---

src/hooks/webui/preload.js

Open `http`/`https` links on default browser. I think it is safe to assume that all links we want to open in the default browser start with `http`. There aren't any other URL kinds on Web UI.
closes #720 
License: MIT

feat: open urls on default browser

---

src/hooks/webui/index.js

Use `before-quit` event from Electron instead of custom event. Probably this will fix the issue on #730 where `app.stop` is called but the app doesn't quit.
License: MIT

fix: close web ui on app.quit()

---

src/hooks/app-events.js
src/hooks/index.js
src/hooks/webui/index.js
src/hooks/webui/preload.js

Prevent any URL that is not from our app to open inside one of our windows. This takes into account the recommendations of [Electron's team](https://github.com/electron/electron/blob/master/docs/tutorial/security.md).
**Update:** content security policy headers seem not to work when web security is set to false.

feat: improve security of electron app

---

src/index.js

Windows 10 requires us to set the user model id **and** to have the app shortcut on the startup menu. This fixes the first part. The latter was already happening.
[Docs for reference](https://electronjs.org/docs/tutorial/notifications#windows).
Didn't find a way to try notifications out without building and installing, but they seem to be working.
License: MIT

fix: set user model id so notifications work on windows 10

---

src/index.js
src/utils/daemon.js

Fixes issue where it couldn't find the IPFS binary to execute commands through `spawn`. We now use `execFile`.
It's a documented limitation: https://electronjs.org/docs/tutorial/application-packaging#executing-binaries-inside-asar-archive
License: MIT

fix: execute IPFS binary in asar

---

src/locales/ca.json
src/locales/cs.json
src/locales/da.json
src/locales/fr.json
src/locales/ko-KR.json
src/locales/nl.json
src/locales/no.json
src/locales/pt.json
src/locales/ru.json
src/locales/zh-TW.json
src/utils/i18n.js

Sync more languages from Transifex.
License: MIT

feat: more languages

---

src/lib/menubar/app/utils/screenshot.js
src/lib/take-screenshot.js

Closes #749.
This way we screenshot all the monitors and save them in separate files. The filename is `TIMESTAMP-Screen #NUM.png`.
License: MIT

fix: screenshots on multiple monitor setup

---

src/index.js
src/lib/index.js
src/lib/menubar/index.js
src/lib/webui/index.js
src/lib/webui/preload.js

- Hide titlebar and integrate traffic-light controls into app. This looks cooler. FACT.
- Show IPFS icon in dock and app switcher when webui window open. You can now tab back into the webui window after jumping to a finder window to get your files.
**Integrated menubar controls**
**App icon in dock and app switcher when webui window open**
License: MIT

feat: improve UX on macOS

---

src/index.js
src/lib/index.js
src/lib/webui/index.js

This fixes a bug from #760 where the `app.dock` object only exists on macOS. We now only use it if is exists, preventing errors on other platforms.
Also, removed the `app` object from the context because it was making the code redundant.
License: MIT

fix: only call dock methods if it exists

---

src/lib/index.js

We just need to change the hooks order to fix this one.
Fixes #767.
License: MIT

fix: open external links in default browser

---

package.json

- update to webui v2.3.1, which updates ipfs-geoip and re-enables locating peers on the map.
fixes #774
License: MIT

fix: gelocation of peers

---

src/lib/download-hash.js
src/lib/register-daemon.js

Check if `ipfsd` it not null before doing the operations. Otherwise it would error.
icense: MIT

fix: always check if IPFSD is not null

---

build/nsis.nsh
package.json
src/lib/index.js
src/lib/protocol-handlers.js
src/lib/second-instance.js

Ref.: #807
- Implements `ipfs://`, `ipns://`, `dweb:/ipfs/` and `dweb:/ipns/` protocol handlers.
- It required some more configuration on Windows since Electron Builder doesn't automatically add the handler configuration to NSIS script (see https://github.com/electron-userland/electron-builder/issues/623).
- On macOS and Linux it is supposed to work. Please try out.

feat: handle ipfs://, ipns:// and dweb: protocols

---

build/nsis.nsh
src/lib/add-to-ipfs.js
src/lib/index.js

Refactors the add handler (for context menus) and added a feature for macOS users: drop files into the icon of the app (not the tray) to add them. It probably won't work if the app is not yet running because the event is fired before starting IPFS.
License: MIT

feat: improve add to IPFS handler

---

build/nsis.nsh

It fixes an issue where we didn't have quotes so we'd
get the short path without spaces. A file called 'Test File.mp3"
would be given as 'TEST-~1.mp3" which would be correctly added
to IPFS but with the wrong name.
License: MIT

fix: 'add to IPFS' on Windows

---

package.json

Change the Windows installer to be a one-click installer and only install per-user. This does not allow system-wide installations, i.e., for all users. I think it's a best practice and it avoids future issues with configuration collisions. This way, each user, if they want, can install IPFS Desktop in the version they want. It also simplifies installation.
License: MIT

feat: one click installer, always per-user

---

package.json
src/index.js
src/lib/auto-updater.js
src/lib/index.js
src/locales/en.json

This PR creates a bit more manual update process. We now notify the user that there is an update available and that IPFS Desktop is going to download the new version in the background. In the end, they get a new notification telling to click on it to update.
It's a bit more manual but it helps us (and the users) get a better understanding of what's happening.
**Edit:** this also fixes #814 by not blowing up the program when there are auto-update errors. We just log them.

feat: update improvements

---

README.md
src/utils/store.js

As per #665, let's enable automatic garbage collector.
License: MIT

feat: enable gc

---

src/lib/register-daemon.js
src/lib/webui/index.js

- Fixes possible edge-case where the Web UI window was already destroyed and we try to close it.
- Do not block quitting. This possibly fixes the tests and the #776 error. If the daemon happens to not exit correctly, we always do a cleanup when it starts
License: MIT

fix: tests & quit click

---

src/utils/daemon.js

Set the range to 200-300. The default was 300-600. Ref: #665
License: MIT

feat: default minimum and maximum connections

---

src/lib/take-screenshot.js

Remove the character `:` from screenshots names because it is incompatible with Windows file system, which would cause some troubles downloading the files.
Fixes #830 
License: MIT

fix: screenshots name incompatibilities

---

package.json
src/lib/menubar/index.js
src/locales/en.json

Closes #832 by adding Desktop and IPFS version to the top of the context menu.
License: MIT

feat: version indicators

---

.travis.yml
test/utils/ipfsd.js

This fixes CI (tests) on Linux. by moving DISPLAY env variable to the main scope.
(We now run the xfvb script in the main scope rather than launching a new shell, that way `npm run test` will see `DISPLAY` if set on linux)
By the way:
- switched to the latest Node.js LTS
- go-ipfs used in tests now inits with 'test' profile and a smaller key (to save some ms)

Restore Linux CI

---

src/lib/index.js
src/lib/language-selector.js
src/lib/menubar/app/index.js
src/lib/menubar/index.js
src/lib/webui/index.js
src/lib/webui/preload.js
src/utils/i18n.js
src/utils/store.js

Updates IPFS Desktop language according to the one set in Web UI. (Ref.: #844)
We can add a notification or something like that to guide users to Transifex when their language doesn't exist for IPFS Desktop.
License: MIT

feat: update menubar language according to web ui's

---

electron-builder.yml

Adds snap output and closes #782. `home` is included in `defaults`.
License: MIT

chore: add snap

---

src/lib/auto-updater.js
src/lib/register-daemon.js
src/utils/index.js
src/utils/quit-and-install.js

gotta clear all listeners on all the windows for quitAndInstall
to work. Now auto-update works as expected on mac.
thanks to the proposed fix on this issue:
https://github.com/electron-userland/electron-builder/issues/1604#issuecomment-372091881
fixes: https://github.com/ipfs-shipyard/ipfs-desktop/issues/851
License: MIT

fix: make quitAndInstall work on macos

---

package.json

webui was failing to upload files. update to 2.4.4 for the fix.
License: MIT

fix: file upload bug

---

README.md

PNG was 777 KB and slowed down README load.
MozJPEG (http://squoosh.app) trimmed it down to 35KB :)

docs(README): optimize hero image

---

src/utils/daemon.js

As per #835, I concluded that, for some reason, IPFS shut down failed and `ipfsd-ctl` wasn't connecting. Although I did not find the true reason, I decided to log the error of `fsck` instead of immediately failing. This way perhaps `start` can connect.
Also, the report is to version 0.6.1. Since then, we've made some tweaks in the shutting down logic, such as defining a timeout. For those reasons, this closes #835.

fix: log fsck error instead of immediately failing

---

src/late/auto-launch.js

This avoids throwing unnecessary errors and checking for their
content.
License: MIT

refactor: check before changing auto-update

---

assets/build/nsis.nsh
src/late/add-to-ipfs.js

Reverts some changes I've made to file adding. Re-adds the flag `--add` so it is easier and clear to know which elements from the args to add. This avoids unnecessary checks.
**Tested and working.Only affects Windows.**
License: MIT

feat: simplify file adding

---

src/late/auto-updater.js
src/late/download-hash.js
src/late/i18n.js
src/late/index.js
src/late/language-selector.js
src/late/take-screenshot.js
src/late/tray.js
src/utils/add-to-ipfs.js
src/utils/index.js
src/utils/notify.js

While building other PR, I noticed the translations weren't available at early stages of startup and that's because i18n returns a promise. Here I change the mechanism so we wait for the translations to be ready.
License: MIT

fix: move i18n to late hooks

---

src/late/auto-launch.js
src/late/download-hash.js
src/late/take-screenshot.js
src/late/utils.js

Only if `activate` returns true, we change the value in the database.
License: MIT

refactor: return status on createToggler

---

.gitignore
assets/build/after-install.sh
electron-builder.yml
package.json

So, this should add the snap hooks for install and removal to add `ipfs` to the `PATH`.
Although, building is failing with "Macro location is not defined". I couldn't find any information on Electron Builder's issues nor on Google. Everything I find is related to C... so... I'm a bit confused with what's happening.
@lidel could you take a look at the code to see if something looks wrong? I'll keep searching to try to find out what's wrong. It seems related to fpm, but I don't change any of its configuration here...

feat: add snap hooks

---

electron-builder.yml

This adds `.tar.xz`, a generic package target that makes things easier for various user groups on Linux:
- **install without package manager** 
- user can just download, unpack somewhere and run without access to root
- testing on unsupported platform becomes much easier
- **create package for distributions that are not supported by our electron build**
- package maintainers can now reuse official `tar.xz` directly, or as a part of packaging pipeline
- to make things more predictable, we hardcoded linux artifact names to follow this convention:
```
${name}-${version}-${os}-${arch}.${ext}
```
examples of produced package names:
```
ipfs-desktop-0.7.2-linux-amd64.deb
ipfs-desktop-0.7.2-linux-amd64.snap
ipfs-desktop-0.7.2-linux-x64.tar.xz
ipfs-desktop-0.7.2-linux-x86_64.AppImage …
```

Add .tar.xz package target

---

electron-builder.yml

This applies to native interfaces such as dialogs.
License: MIT

feat: support macOS dark mode

---

assets/locales/en.json
src/late/ipfs-on-path/index.js

Closes #933. If it's macOS or Windows **and** `ipfs` cannot be found in `PATH`, add it. Otherwise, the user can add manually on Settings. What about Linux? We always need permission to modify `path`/`/usr/local/bin` so checking the toggle manually option is the only way for now and the least intrusive.
License: MIT

feat: don't ask to add ipfs to PATH

---

src/utils/daemon.js
test/spec.js

- the test occasionally fail in ci as we're not giving the app
time to update the config
- add a try/catch around the write conf, because you never know.
cherry-pick'd back from the 0.7.3-dev branch.
License: MIT

chore: await delay in tests. Handle config write error.

---

src/late/register-daemon.js
src/late/webui/connection-status.js
src/late/webui/preload.js

Restarts the daemon when the connection gets changed. To test it, try turning off and on the WiFi or switching network.
Closes #930.
License: MIT

feat: restart daemon when connection changes

---

package.json
src/late/register-daemon.js
src/late/webui/preload.js

Adds `restartIpfs` function to `window.ipfsDesktop` object.
- See https://github.com/ipfs-shipyard/ipfs-webui/pull/1050
License: MIT

feat: add restart ipfs function

---

src/late/tray.js

Allows to open the menubar and Cmd+Q to quit. Not possible before.
License: MIT

feat: add Cmd+Q accelerator on macOS

---

assets/locales/en.json
src/late/download-hash.js
src/late/take-screenshot.js
src/late/tray.js

Many users might not want to use the global shortcuts. If they don't enable them, they won't have access to the features. This way, the features are always accessible even when they don't have the global shortcuts enabled.
**Todo in a future PR:** shortcuts **only** when the menubar is open like Cmd+Q.
License: MIT

feat: add shortcuts actions to menu

---

src/dialogs/ipfs-not-running.js
src/late/auto-updater.js
src/late/index.js
src/late/register-daemon.js
src/late/tray.js
src/utils/quit-and-install.js

Use functions instead of events for **actions**.
License: MIT

refactor: use functions instead of events

---

.travis.yml
package.json
src/late/webui/index.js

Made some changes on `ipfs-or-gateway` which now supports multiple retries. It's configured for 3 retries (default) and 5 minutes of timeout (not default, but we know how the gateway can be at this time...).
Also updates the macOS version because it was failing since it was 'old'.
This **won't** solve everything. There might be timeouts anyway.
Ref.: #973

chore: reduce ci issues with timeouts and retries

---

src/daemon/index.js

Hopefully fixes #974. Since we already have the timeout on `ipfsd.stop`, this won't add much time when quitting desktop.
License: MIT

fix: only quit after stopping daemon

---

src/webui/index.js

Prevents opening web ui when clicking the dock icon
because it is only active when there's an window open.
License: MIT

fix: do not open webui when clicking the dock icon

---

.travis.yml

The latest beta version didn't build a `.snap` package because `snapcraft` wasn't installed. It was before. Probably an update on Travis Ubuntu version caused this.
License: MIT

chore: add snapcraft

---

electron-builder.yml

The [configuration](https://www.electron.build/configuration/snap) for `snap` says:
> snap target by default publishes to snap store (the app store for Linux). To force publishing to another providers, explicitly specify publish configuration for snap.
Perhaps this is the reason why publishing is failing on Linux since the logs show there is an error while publishing to snap store.
This was a change introduced in [Electron Builder v21.0.5](https://github.com/electron-userland/electron-builder/releases/tag/v21.0.15). They should have published it as a breaking change because... it is a breaking change.
License: MIT

chore: do not upload to snap store

---

.babelrc
package-lock.json
package.json
src/app-menu.js
src/exec-or-sudo.js
src/ipfs-on-path/scripts/backup.js
src/ipfs-on-path/scripts/consts.js
src/ipfs-on-path/scripts/install.js
src/ipfs-on-path/scripts/uninstall.js
src/npm-on-ipfs/package.js
src/webui/connection-status.js
src/webui/preload.js
src/webui/screenshot.js
test/e2e/launch.e2e.js
test/e2e/utils/include.js
test/e2e/utils/ipfsd.js

1. Refactors the remaining `require`s into `import`s.
2. Builds source maps when Babel is run.
3. Starts Electron after running Babel.
4. Removes babel `preset-react`.
In the future I should look into a way to reload Electron when the files are changed.
License: MIT

refactor: replace requires by imports

---

package.json
src/webui/preload.js

Increases the draggable area of IPFS Desktop. The new draggable area is (anywhere in the light blue area can be clicked to drag and move the window around):
It also fixes the issues when focusing the buttons/input.
- Needs https://github.com/ipfs-shipyard/ipfs-webui/pull/1138
- Fixes #1066
License: MIT

fix: increased window draggable area

---

.gitignore
src/daemon/index.js
src/ipfs-on-path/scripts/bin-win/ipfs.cmd
src/ipfs-on-path/scripts/ipfs.sh

This fixes the issue caused by having IPFS_PATH in the same directory as the app code. That would fail in multiple circumstances:
1. When the app was updated, IPFS_PATH would get deleted.
2. macOS gatekeeper paths randomization for security purposes creates a read-only directory for the app files when the app isn't executed from secure locations (such as ~/Applications) and it would make it fail.
Closes #1077.
License: MIT

fix: move IPFS_PATH to ~/.ipfs-desktop

---

README.md

Adds paths for config on Linux and notes about path in dev mode (which may confuse potential contributors in the beginning).

docs: notes on location of config files

---

package.json

This is a workaround for now before finding why sometimes mocha does not exit even after tests are done, which makes CI fail.
Probably some IPFS cleaning up that takes too long or gets stale.
License: MIT

chore: force exit mocha after tests complete

---

assets/locales/en.json
src/daemon/daemon.js
test/e2e/launch.e2e.js

Fixes #1091
On the case there is an array of API or Gateway addresses and one or more of them collide with already busy ports, we show this message:
Users that have multiple addresses for API/Gateway already changed the configuration on their own and know how to solve this kind of issues.
License: MIT

fix: allow multiple gateway and api ports

---

src/exec-or-sudo.js
src/ipfs-on-path/index.js

This makes adding `ipfs` to PATH fail silently when it wasn't the user triggering the action, i.e., it fails silently only when try to add the binary to the PATH the first time we launch IPFS Desktop.

fix: fail silently 'IPFS' on path auto action

---

src/ipfs-on-path/index.js

Fixes #1113. There was no default value so it would fail.
License: MIT

fix: undefined on function argument

---

src/daemon/index.js

fix: call log.fail instead of logger.error

---

src/argv-files-handler.js
src/index.js
src/protocol-handlers.js
src/second-instance.js
src/webui/index.js

Opens Web UI on second instance. This partially addresses #1153. When trying to open the app again, the Web UI window opens up.
Personally, I don't like this code really much because I had to move some other parts to fit them all in a single `second-instance` handler. We only open the Web UI if no protocol, nor file was handled.
License: MIT

feat: open web ui on second instance

---

package-lock.json
package.json
src/index.js

Add [`v8-compile-cache`](https://github.com/zertosh/v8-compile-cache) for better performance. Many of the suggestions online to improve Electron's performance is by adding this compile cache. I thought about giving it a try. It actually seems a bit faster after the first launch here.
License: MIT

feat: v8 compile code cache

---

package.json

Relevant release notes can be found on [v2.5.5](https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.5.5).

feat: web ui 2.5.7

---

electron-builder.yml

This patch gives IPFS Desktop the correct icon and puts it in the correct category in the desktop applications menu.

feat: set icon and category in Linux .desktop file

---

package.json
src/webui/index.js
src/webui/preload.js

This addresses #1196 by changing to a blank page whenever the window is not visible. For this, we use the Page Visibility API.
Requires https://github.com/ipfs-shipyard/ipfs-webui/pull/1259.
This reduced **significantly** the CPU usage on my end.
License: MIT

fix: use blank page when window isn't active

---

package-lock.json
package.json
src/auto-launch.js

Auto Login was working... kinda of. According to the reports by @alexhenrie, auto launch on startup was not working on login since our installation path has a space on it and the [package](https://github.com/Teamwork/node-auto-launch/issues/99) we're using is not escaping that properly.
Unfortunately, [`node-auto-launch`](https://github.com/Teamwork/node-auto-launch/issues/99) hasn't been updated since 2017 and since then, Electron got its own capabilities to add login items for Windows and macOS so we can use that feature.
This changes the following:
- Stops using `node-auto-launch` for managing our launch at login state. It is still a required dependency so we can remove previous entries created by it. It will be removed on 0.10.0.
- Starts using `app.setLoginItemSettings` to manage …

feat: improve auto launch at login

---

src/auto-launch.js

There's no reason for the IPFS Desktop file in `~/.config/autostart` to look ugly.

feat: give the IPFS startup entry an icon

---

assets/locales/en.json
src/add-to-ipfs.js
src/argv-files-handler.js
src/tray.js

With this PR, we get back the feature of copying a shareable link to the clipboard when adding files to our node via the IPFS icon that sits on the menubar on macOS or to the shortcut of the app on Windows.
In addition, I cleaned up the locale messages, removing some that are not used anymore and updating the ones we have for this notification in particular. I will create a separate PR organizing the translation file a bit more.
We now add all files at once and give only **one notification**. If the user drops multiple files, we create an object linking to all of them, which is used for the shareable link and when clicking on the notification.
Closes #1218.
License: MIT

feat: copy link to clipboard when adding to ipfs

---

src/index.js

This aims to fix #1267. I don't know how to reproduce the error so I'm not sure if this is going to fix it. Those errors never have stack trace so it's hard to understand them. However, I believe this might fix it because it just ignores errors with `net::` on it generated by unhandled rejections and exceptions.
License: MIT

fix: ignore net:: errors

---

src/tray.js

This just fixes some weird change I made on https://github.com/ipfs-shipyard/ipfs-desktop/blob/48ef20ec6eba628fd5b75bc2e84e6f5b95e084a1/src/tray.js: start with the offline icon.
License: MIT

fix: start with off icon

---

README.md

fix: broken link to "locales" in Readme

---

.travis.yml
package-lock.json
package.json
test/e2e/launch.e2e.js

chore: go-ipfs v0.4.23

---

README.md

docs: clarified release process

---

assets/locales/en.json
src/auto-updater/index.js

Adds a notification when the user clicks 'Check for Updates...' and there is an update available. Right now, we either show the notification when there is **no update available** or we **finished downloading the update**, which may take some time.
Not sure if this addresses #1378 but I'm pretty sure it will improve UX anyways.
License: MIT

feat: notify when the update is available

---

src/daemon/index.js

This fixes the situation where the user changed the configuration by themselves and removed the path variable or changed its type to something other than string.
The previous check would only update the path is it was an empty string. This way, any invalid path is overwritten.
License: MIT

fix: write path when it does not exist

---

src/daemon/consts.js
src/daemon/index.js
src/dialogs/ipfs-not-running.js

Fixes a circular dependency between the dialogs and daemon which was causing `showDialog` not to be available.
License: MIT

fix: circular dependency between dialogs and daemon

---

assets/locales/en.json
package.json
src/auto-updater/index.js
src/dev-app-update.yml

- Closes #1378 
- Partially addresses #1210 ( we show a button to check release notes )
This improves the experience while updating. Here are two dialog screenshots and please review the code for more copy.
**Note:** Electron's logo is replaced by IPFS Desktop's in production.
- User **clicked** 'Check for Updates'
- If available, receives dialog (with close and read release notes buttons).
- If not available, receives dialog (with close and read release notes buttons).
- If error, receives dialog telling to check the Internet connection.
- Update downloaded, receives dialog with button to restart IPFS Desktop.
- Auto updater found an update (every 12 hours)
- If available, nothing, downloads in background.
- If not available, nothing happens.
- If error, gets logged internally.
- Update …

feat: improved update experience

---

assets/locales/en.json
src/run-gc.js
src/tray.js

Supports running the GC from the menubar. This was a feature that was lost during the revamp. Closes #1355.
Note: the Electron icon is replaced by IPFS Desktop's icon on the final version.
License: MIT

feat: run garbage collector

---

package.json
src/create-toggler.js
src/webui/index.js
test/unit/create-toggler.spec.js

- Closes #1290.
- Should be tested with https://github.com/ipfs-shipyard/ipfs-webui/pull/1381.
With this change, we send the result from `os.platform()` from the main process to the renderer process so we can actual know which platform we're using.
License: MIT

fix: start on login

---

assets/locales/en.json
src/dialogs/errors.js
src/ipfs-on-path/index.js
src/move-repository-location.js

This adds the possibility of adding custom error messages. I also updated some places to show specific error messages instead of general ones.

feat(ux): better error messages

---

src/tray.js

This is a small UX nitpick that I thought that makes sense. Please correct me @jessicaschilling @lidel: I added a separator between the 'Open' actions and the other ones. It feels much better now.
Before:
Then:
License: MIT

feat(ux):  separate open from other actions

---

appveyor.yml
package.json
src/daemon/config.js
src/webui/index.js

This bumps go-ipfs version to 0.5.0-rc1 in preparation for 0.5 release.
Small set of fixes was required:
- Status check
- switched API calls from `GET` to `POST` (https://github.com/ipfs/go-ipfs/pull/7097)
- Bundled ipfs-webui loaded via Electron's BrowserWindow
- `Origin` header: a proper value is set instead of removing it
- sending `ipfs-desktop/${version}` in `User-Agent` header
cc @hacdias @Stebalien  https://github.com/ipfs/go-ipfs/issues/7109

feat: support for go-ipfs 0.5

---

src/common/store.js

Fixes the flags we pass to the ipfs daemon. After merging #1392, my daemon wouldn't start because the `--migrate` flag was malformed. We don't need the `=true`. I looked at ipfsd-ctl tests and it seems the flags now should be set like this. Without migrating, the boot would hang.
It may be **breaking** for users that changed the flags by themselves. For simplicty, I just **replaced** the flags in the configuration to:
```javascript
[
'--migrate',
'--enable-gc',
'--routing', 'dhtclient'
]
```
This can be added as a breaking change on the release notes. Probably only some power users know about this and changed it so they'll know what to do once they see this.
License: MIT

fix(BREAKING): ipfs daemon flags

---

assets/locales/en.json
package.json
src/auto-launch.js
src/dialogs/errors.js
src/download-cid.js
src/ipfs-on-path/index.js
src/npm-on-ipfs/index.js
src/npm-on-ipfs/package.js
src/take-screenshot.js
src/tray.js
src/utils/create-toggler.js
src/utils/exec-or-sudo.js
src/utils/setup-global-shortcut.js
src/webui/preload.js
test/unit/create-toggler.spec.js
test/unit/mocks/webui.js

This PR removes the Desktop settings from the Web UI panel! Related to #1389.
- See https://github.com/ipfs-shipyard/ipfs-webui/pull/1445 **merged**
- macOS guidelines prefer the term 'Preferences', others OSes users prefer 'Settings'
- Adds the settings under 'Preferences' (macOS) or 'Settings' (others)
- Some that might require more explanation get an information dialog before installing/enabling.
- Errors are now more visible (user gets a dialog). Before, Web UI only said: "error while enabling X".
- Closes #1436 (disables web ui links when node is offline)
License: MIT

feat(ux): move preferences to menubar

---

src/daemon/config.js
src/daemon/daemon.js

`ipfs repo fsck` seems to have been deprecated (https://github.com/ipfs/go-ipfs/commit/288a83ce7dcbf4a2498e06e4a95245bbb5e30f45) in the meanwhile so our logic wasn't working.
I changed it so now we manually check if it's a connection refused error. If so, check if there's a config file. If so, remove the api file.
If no config file, then it's a remote api connection, show error to the user.
License: MIT

fix: repo fsck is deprecated

---

package.json
src/common/store.js

Refactors store to use the package defaults and migrations to allow for
easy configuration migrations and defaults. The migrations use the package
version, hence the bump.
License: MIT

refactor: use store migrations and defaults

---

assets/locales/en.json
src/tray.js
src/webui/index.js

See https://github.com/ipfs-shipyard/ipfs-desktop/issues/1153#issuecomment-616243802.
Adds the option to open Web UI automatically on startup. This is enabled by default when the OS is neither Windows, nor macOS to help users that do not have a tray icon.
License: MIT

feat(ux): open Web UI at launch on Linux

---

src/webui/index.js
src/webui/preload.js

Fixes #1451. Keeps track of the last opened page so every time we need to refresh because a change on the IPFS status, we can keep the user on the same page. The visibility (`/blank` handling) is taken care on the `preload.js`.
License: MIT

fix: keep track of last opened page

---

src/dialogs/prompt/index.js

Show dock while the prompt is visible.
License: MIT

fix(ux): show dock when prompt is visible

---

package-lock.json
package.json

This PR updates ipfs-webui bundled with ipfs-desktop to [v2.8.0](https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.8.0)
Brings refreshed Peers map and fixes drag&drop issues from  #1287

feat: ipfs-webui v2.8.0

---

package-lock.json
package.json

For some reason CI included 0.4.23, ignoring the go-ipfs key in
package.json. Hopefully this will fix it.

fix: go-ipfs 0.5.0 with go-ipfs-dep 0.5.0

---

src/ipfs-on-path/scripts/bin-win/ipfs.cmd

fix: ipfs on PATH on windows with spaces in binary path

---

README.md

This adds note to README about tray icon on linux.
Context: #1153

docs: linux tray troubleshooting

---

README.md

This PR updates links and badges with stats to point at 0.11.0 release.
This should be merged when we publish release and close #1415

chore: v0.11.1 release links in README

---

src/webui/preload.js

Closes #1287
During some electron update, this function was probably left behind and didn't change from using callbacks to promises.

fix: open directory from webui

---

.github/ISSUE_TEMPLATE/bug_report.md

This PR improves Bug reporting template by adding instruction on where to find error logs and asking reporter to attach them to the bug report.
This should save us the usual 1-2 roundtrips in most of  cases.
Thank you to @achingbrain for inspiration :-)

docs: improve error reporting template

---

pkgs/macos/notarize-build.js

electron-builder skips signing in PRs (https://github.com/electron-userland/electron-builder/commit/e1dda14) so we should skip notarization as well to speed up the CI and avoid unnecessary errors ([example](https://travis-ci.com/github/ipfs-shipyard/ipfs-desktop/jobs/333268431#L323-L327)).

fix(ci): skip notarization if signing was skipped

---

src/auto-updater/quit-and-install.js
src/index.js

Fixes #1508, fixes #1496, fixes #1375
- I'm not able to test this for sure because autoUpdater doesn't work on dev mode.
The problem was that the autoUpdater was trying to access the `stopIpfs` from the context (`ctx` variable), but that would only be initialized with the functions after `setupDaemon` has been executed.

fix: added daemon functions to the auto-updater

---

package.json

https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.9.0
@rafaelramalho19 FYSA this is release I created in hope to ship in go-ipfs 0.6. 
(I am creating PRs for all repos listed in https://github.com/ipfs-shipyard/ipfs-webui#releasing because I forgot the last time and v2.8.0 did not propagate everywhere)

feat: ipfs-webui v2.9.0

---

.travis.yml
electron-builder.yml

This PR fixes recent CI failures by reverting #1156 
This removes login to the third party service during our CI build and publishes `.snap` package to github release, instead of snapcraft.io, which breaks CI when tokens expire ([example](https://travis-ci.com/github/ipfs-shipyard/ipfs-desktop/jobs/346643502#L497)).
- our CI should not log into a third party service on every build
- publishing to third party package stores should not determine if release build is successful or not 
- it should be a separate step, after successful release build

fix(ci): disable snap login and publishing

---

src/auto-updater/index.js

fix: windows auto-update feature when selecting install for all users

---

package-lock.json
package.json

This PR bumps go-ipfs to 0.6
Before merging:

feat: go-ipfs 0.6

---

package.json

Release Notes:
* https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.10.0

chore: bump webui version

---

src/daemon/config.js
src/daemon/daemon.js
test/e2e/launch.e2e.js

Fixes https://github.com/ipfs-shipyard/ipfs-desktop/issues/1631

fix: uppercase Discovery.MDNS.enabled in default config

---

README.md
pkgs/chocolatey/update.js

Automation set up on AppVeyor [is broken](https://github.com/ipfs-shipyard/ipfs-desktop/pull/1360#issuecomment-598348947), let's go with manual steps for now.
I've also added Snap package, since we stopped pushing automatically some time ago (https://github.com/ipfs-shipyard/ipfs-desktop/issues/1551)

docs: update chocolatey checklist

---

README.md

This PR updates the "No tray icon on Linux" section in `README.md` to account for changes in Electron.
cc #1153

docs(readme): update tray troubleshooting on Linux

---

electron-builder.yml
package.json

Closes #1659 and unblocks v0.13
- turns out removing duplicate go-ipfs from `asar` archive saves us "only" ~1MB, so not worth it
- we could remove it, but it would break [path detection](https://github.com/ipfs/npm-go-ipfs/blob/v0.7.0/src/index.js) which expect binary to be present (and if we remove it from `asar` no binary will be found). for sake of keeping codebase simple, lets leave it as-is.
I am going to merge this and re-create release draft for v0.13 with smaller binaries.
Then, we will smoke-test them to see if linux/macOS/Windows work as expected.

fix: ensure small asar archive

---

CHANGELOG.md

docs: changelog for 0.13.0

---

assets/build/nsis.nsh
electron-builder.yml
src/auto-updater/index.js

This PR aims to close #1570
Context: https://github.com/ipfs-shipyard/ipfs-desktop/issues/1570#issuecomment-705081315
- We won't know for sure, unless we  test in production, but we don't need to use this app
- I created [sandbox electron app](https://github.com/lidel/electron-updater-altschmerz), which uses electron-build config similar to one in ipfs-desktop and basically the same CI setup
- Next step is to copy autoupdate code from ipfs-desktop to that app, and see how it behaves on Windows.
- no, still broken https://github.com/ipfs-shipyard/ipfs-desktop/pull/1679#issuecomment-705569228
- fix: https://github.com/ipfs-shipyard/ipfs-desktop/pull/1679#issuecomment-705630973
cc @jessicaschilling @rafaelramalho19

fix: windows auto-update

---

.github/workflows/snapcraft.yml
README.md

This PR aims to remove the need for manually publishing snap to Snapcraft.
Closes https://github.com/ipfs-shipyard/ipfs-desktop/issues/1551
- The workflow is triggered when a new release is published.
- It assumes `.snap` is attached to the release, 
- downloads it 
- and then publishes it to Snapcraft at snapcraft.io/ipfs-desktop

feat(ci): automated Snapcraft publishing

---

src/common/notify.js
src/daemon/config.js
src/dialogs/errors.js
src/tray.js

This PR
-  replaces deprecated `openItem` with `openPath` (closes #1676 & closes  #1677)
necessary due to https://github.com/electron/governance/blob/master/wg-api/spec-documents/shell-openitem.md
- makes some links more useful by linking to specific version
- limits the length of URL for bug reporting to ~2k characters (closes #1530)
Edit: also closes #1685, closes #1686, closes https://github.com/ipfs-shipyard/ipfs-desktop/issues/1688.

fix: openItem errors

---

src/take-screenshot.js

This ensures the CID is properly passed to copied link, and that filename is preserved when a single screen setup is used (produces single screenshot). Switched to reliable gateway, as share.ipfs.io is not maintained.
We also avoid low level pinning  (MFS is enough) and ensure the produced CID is the same as on CLI (avoiding problems described in https://github.com/ipfs-shipyard/ipfs-webui/issues/676).

feat: screenshot improvements

---

src/add-to-ipfs.js

This PR refactors code to fix bugs caused by [js api changes](https://blog.ipfs.io/2020-02-01-async-await-refactor/).
The sneaky one: the way we pass template changed in a way that failed silently:
https://github.com/ipfs/js-ipfs/blob/8cb8c73037e44894d756b70f344b3282463206f9/packages/interface-ipfs-core/src/object/new.js#L33-L40
so instead of unixfs, we were patching untyped object, which gateway was unable to render.
@rafaelramalho19 
I've pushed 1 line fix to your branch and created this PR to include our fixes.
Same code is used for different variant on each OS, so we need to test both.
Closes #1684

fix: OS integrations for quick file import

---

CHANGELOG.md
README.md

Changelog and readme updates for v0.13.1, including addition of manual testing steps.
@lidel - can you please fill in the details for protocol handler test? Afraid my memory is sketchy ...

docs: updates for 0.13.2

---

README.md
package.json

This PR makes instance started via `npm start` read `package.json` and that makes Electron to use config from `~/.config/IPFS Desktop` instead of `~/.config/Electron`.
Goal here is to have the same behavior in dev as  in packaged production version, reducing the surface for human error (eg. I was removing `~/.config/IPFS Desktop` between tests while `~/.config/Electron` remained with broken config)
@hacdias @olizilla cc fyi (I remember this  being an issue in past, this seems to be the fix)

fix: use correct config path during development

---

.github/workflows/chocolatey.yml
.github/workflows/ci.yml
README.md
pkgs/chocolatey/README.md

This PR automatically updates https://chocolatey.org/packages/ipfs-desktop when a new release is published.
Closes #1674 
- done: https://chocolatey.org/packages/ipfs-desktop/0.13.2
**Note:**  IPFS Desktop package is trusted and bypasses human moderation if the automated review checks pass. The automated review checks are typically finished within 1-2 hours or less after the package has pushed, depending on the verifier queue.

feat: automated Chocolatey publishing

---

DEVELOPER-NOTES.md
README.md

Closes https://github.com/ipfs-shipyard/ipfs-desktop/issues/1670.
- Rewrites README overall, primarily focusing on better explanation of features
- Updates throughout for outdatedness
- New screenshots
- Moved release checklist into DEVELOPER-NOTES.md to avoid wall of scary text
- Copy/clarity edits, etc etc
Note: Once this is approved/merged, I'll add some highlights (primarily features list) to https://docs.ipfs.io/install/ipfs-desktop/ in a separate PR in the docs repo.

feat: rework readme

---

README.md

the syntax `brew cask install <pkg>` is now disabled. as per: https://github.com/Homebrew/discussions/discussions/340#discussioncomment-232364

Fix Homebrew instructions

---

src/dialogs/prompt/template.js

Closes https://github.com/ipfs-shipyard/ipfs-desktop/issues/1728.
This PR explicitly specifies `utf-8` content-type in the template for the "Download..." dialog so non-roman languages don't blow out.
Tested in Mac Big Sur **only**; would appreciate a look in Linux/Windows.

Explicitly specify content-type in prompt template

---

assets/locales/en.json
package-lock.json
package.json
src/enable-pubsub.js
src/index.js
src/tray.js
test/e2e/launch.e2e.js

Part of https://github.com/ipfs-shipyard/ipfs-desktop/issues/1647
Adds a menu preference option to enable pubsub which adds a flag to the ipfsd-ctl options for startup.
Question: should this prompt a restart, given that the setting won't take effect until ipfs has been been restarted?
Bug: I'm getting the enabled/disabled message logged twice when clicking on the menu item, not quite sure why :
```
$ npm start
> ipfs-desktop@0.13.2 start
> cross-env NODE_ENV=development electron .
2021-01-19T16:19:06.988Z info: [meta] logs can be found on /Users/andrewnesbitt/Library/Application Support/IPFS Desktop
2021-01-19T16:19:10.560Z info: [web ui] window ready
2021-01-19T16:19:10.560Z info: [tray] starting
2021-01-19T16:19:10.607Z info: [tray] started
2021-01-19T16:19:10.608Z info: [ipfsd] start …
```

feat: enable pubsub via settings menu

---

assets/locales/en.json

As requested by @jessicaschilling in https://github.com/ipfs-shipyard/ipfs-desktop/pull/1739#issuecomment-763893741

Tweak title of npm on ipfs preference

---

assets/locales/en.json
src/automatic-gc.js
src/common/store.js
src/daemon/daemon.js
src/index.js
src/tray.js

Closes #1647 (now that #1735 has been merged)
Very similar approach to #1735

feat: disable/enable gc via settings menu

---

assets/locales/en.json
src/enable-namesys-pubsub.js
src/enable-pubsub.js
src/index.js
src/tray.js

Part of #1647
Very similar approach to #1735

feat: enable ipns over pubsub via settings menu

---

src/auto-updater/index.js
src/common/consts.js

This PR:
- disables autoupdate on platforms other than macOS, Windows and AppImage, solving problem described in #1671
- on platforms that do not have built-in autoupdate we assume a third-party package manager is used
- The `About → Check for Update..` menu item is still present, but instead of built-in check it opens https://github.com/ipfs-shipyard/ipfs-desktop/releases/latest
Closes #1671 and also historical  #1683 / #1274 / #928

fix: autoupdate only on supported platforms

---

src/webui/index.js

Fixes #1741 by defaulting `openWebUIAtLaunch` to `true`.
This change is particularly useful for users who have extensions that declutter their system/tray which may initially hinder access to the Desktop app.

fix: default Open at Launch to true

---

src/tray.js

- avoid `TypeError: event.preventDefault is not a function`  (closes #1762)
- double-click opens webui (closes #1764)
- tray fixed, but entire windows experience is so bad I don't know if things are broken or just slow
- it blows my mind that 20 years later Windows platform still has janky tray icon code: it does not disappear when you kill the process, you can get duplicate "phantom"  one... :exploding_head: :exploding_head:  knowing its broken everywhere in some way or another makes me feel bit better about mess on linux (#1153) :trollface:

refactor: tray click events

---

src/tray.js

"ipfs-on-path" opt-in feature aims to add `ipfs` binary to `PATH` on every platform. 
Unfortunately that is brittle, buggy, way better if user does this by hand for now.
We have a bunch of creative hacks that make it work most of the time, but after looking how we do it, I don't feel comfortable keeping this as a feature:
-  relies on brittle scripts which break over time and degrade user experience
-  we don't have bandwidth for maintaining this feature for all platforms
- windows requires powershell, which a lot of users dont have on PATH (sic!)
- linux requires polkit, not every distro uses that
- even so, iiuc it is not even possible to make it work in sandboxed contexts like Snap or AppImage
- adding to global PATH is a security-sensitive task and I don't think a desktop app should …

chore: deprecate ipfs-on-path

---

README.md

AppImage is the only one that does autoupdates on Linux without a third-party package manager.
Pointing less sophisticated users at it may be beneficial, 
as they avoid issues with things like Snap which does not look reliable these days (https://github.com/ipfs-shipyard/ipfs-desktop/issues/1774#issuecomment-787210407)
cc @johnnymatthews  @olizilla @jessicaschilling

docs: promote AppImage for Linux

---

src/ipfs-on-path/index.js

I don't believe windows scripts are safe, this ensures they won't break ipfs-desktop boot process.

refactor: ipfs-on-path should never fail on boot

---

assets/locales/en.json
src/dialogs/prompt/index.js
src/download-cid.js

This displays error details when write to a destination directory fails, and ensures stored files are contained within destination dir.
Should improve UX in situations where user picked read-only directory, run out of disk space etc. 
cc @schomatis

fix: print useful error on write fail

---

.github/workflows/snapcraft.yml

This PR aims to fix publishing to https://snapcraft.io/ipfs-desktop + add ability to trigger job manually.

fix: snapcraft ci job

---

src/add-to-ipfs.js
src/webui/index.js
src/webui/preload.js

This PR aims to fix UX issue and close  #1815, but is bit tricky for me personally as I don't own any Windows box.
Need to figure out how to test this.
1. Install IPFS Desktop
2. Right click on a file and "Add to IPFS"
3. Click on the popup displayed by windows
Expected behavior is that Files screen will be opened.

fix: click on notification after import of files

---

package-lock.json
package.json

RELEASE NOTES: https://github.com/ipfs/go-ipfs/releases/tag/v0.9.1
Closes https://github.com/ipfs/ipfs-desktop/issues/1872

fix: go-ipfs 0.9.1

---

src/webui/index.js
src/webui/preload.js

Electron 12 introduced context isolation enabled by default. Thus, the `window` object that the preload script and the Web UI page have access to are different. Hence, Web UI cannot detect if it's running inside Desktop. ~Disabling Context Isolation fixes the issue.~ Using the new `contextBridge` function fixes the issue, as well as exposing the language update function through the global object.
Open Settings, go to the Analytics part and check the events list. If you don't see `SCREENSHOT_TAKEN` (among others) is because of this.
License: MIT

fix: use context bridge

---

.github/workflows/ci.yml
package.json

This should stabilize CI by reducing the number of times we fetch the same version of ipfs-webui :grimacing:

fix(ci): cache ipfs-webui

---

src/analytics.js

make it work with a read-only node_modules

fix: analytics storage_path in $HOME/.ipfs-desktop

---

src/common/store.js

[go-ipfs 0.10.0 shipped](https://github.com/ipfs/go-ipfs/releases/tag/v0.10.0) with support for running  `ipfs daemon` with custom `--agent-version-suffix`  (https://github.com/ipfs/go-ipfs/pull/8419)
This PR adds `--agent-version-suffix=desktop` and cleans up the way we set `--routing`
IPFS Desktop nodes will now announce themselves as `go-ipfs/0.10.0/desktop`

chore: default --agent-version-suffix and --routing

---

electron-builder.yml

Removing `zip` to fix UX issue where users are confused by "broken zip installer".
See rationale: https://github.com/ipfs/ipfs-desktop/issues/1922#issuecomment-980034904
Closes #1922

fix: remove zip for Squirrel.Mac

---

src/index.js

Fixes #1927 by ensuring that the context has `.manualCheckForUpdates` before the tray is started.
License: MIT

fix: add .manualCheckForUpdates before tray startup

---

src/common/consts.js

Electron is a dev dependency. However, `devDependencies` is not available after packaging the app and it will throw an error right after starting IPFS Desktop.
The most fail proof way to obtain it is via `process.versions.electron`: https://www.electronjs.org/docs/latest/api/process#processversionselectron-readonly.
License: MIT

fix: electron version constant

---

assets/locales/en.json
src/webui/index.js

Replaces the deprecated event 'crashed' by 'render-process-gone' and actually use the information correctly. In addition, I removed the `event.toString()` from the 'unresponsive' event because it does not contain additional info.
References:
- https://github.com/electron/electron/pull/23096
- https://www.electronjs.org/docs/latest/api/web-contents#event-unresponsive
- https://www.electronjs.org/docs/latest/api/web-contents#event-render-process-gone
Noticed this because on [#1951](https://github.com/ipfs/ipfs-webui/issues/1887), the logs just say `[object Object]`...
License: MIT

feat: better handling of 'unresponsive' event

---

package-lock.json
package.json
src/add-to-ipfs.js
test/unit/add-to-ipfs.spec.js
test/unit/fixtures/dir/within/hello-ipfs.txt
test/unit/fixtures/hello-world.txt
test/unit/mocks/electron.js
test/unit/mocks/logger.js
test/unit/mocks/notify.js

Fixes #1973 and adds unit tests. I also stopped using `object.addLink` and used the same strategy as in https://github.com/ipfs/ipfs-webui/pull/1890.

fix: use new glob source API

---

src/daemon/config.js

Fixes #1990.
More context in #1990.

fix: remove default lower bound from gateway and api port lookup

---

assets/locales/en.json
package-lock.json
package.json
src/daemon/daemon.js
src/daemon/index.js
src/daemon/migration-prompt.js
src/dialogs/errors.js
src/dialogs/prompt/index.js
src/dialogs/prompt/styles.js
src/dialogs/prompt/template.js

feat: show repo migration (go-ipfs 0.12.0)

---

src/daemon/daemon.js

go-ipfs will try to fetch migrations from HTTP, but if that fails, it falls back to download over IPFS.
Such error is not permanent, so we clear `isErrored` flag when error is followed by a line with `Fetching with IPFS`.

fix: migration fallback to ipfs

---

src/dialogs/errors.js

This PR makes issues created by users from the error dialog more useful  by setting the title to the very first like in the stack trace, which usually includes a useful error message.

fix: gui error report title

---

CHANGELOG.md
README.md

docs: 0.20.x

---

assets/locales/en.json

Closes #1999 by removing "click here" prompt. 
This way there is no explicit expectation that clicking should do anything.

fix: ux of notification after file import

---

README.md

docs: debian 11

---

assets/locales/en.json
src/daemon/daemon.js
src/daemon/index.js
src/daemon/migration-prompt.js

This PR removes false-negatives when "error" is printed by `ipfs daemon` but it does not kill the process.
This updated logic will set `isErrored` only when `ipfs daemon` is truly unable to continue:
- checks if process behind spawned `pid` is alive, and shows "startup error" window when process is dead
- removes false-negatives caused by migration code or other "soft"   errors printed to the console
- turns the `isErrored` state  into generic "daemon startup has failed" one
Closes #2023
Closes #2018
Closes #2027 
Closes #2017
Closes #2028
+ prob many more
- fetching from IPFS works as expected
- it works fine, subprocess is `null`, skipping `pid` checks

fix: proper catch-all daemon startup errors

---

src/daemon/config.js
test/e2e/launch.e2e.test.js

Closes https://github.com/ipfs/ipfs-companion/issues/1068
Explainer in https://github.com/ipfs/ipfs-companion/issues/1068#issuecomment-1074330153

fix: ipfs-companion rpc api in go-ipfs <0.13

---

src/daemon/config.js
test/e2e/launch.e2e.test.js

Closes #2039 by applying lowpower values to `Swarm.ConnMgr` for new and existing users:
```
config.Swarm.ConnMgr.GracePeriod = '1m'
config.Swarm.ConnMgr.LowWater = 20
config.Swarm.ConnMgr.HighWater = 40
```
I've run it for a while and works fine, peer count jumps to few hundreds when needed, and then dials down after a minute or two. 
This is a pretty safe one-time migration.
We can always adjust it further in the future releases.

fix: lowpower config in Swarm.ConnMgr

---

assets/locales/en.json
src/daemon/config.js
src/daemon/daemon.js

fix: detect invalid or corrupted repository

---

src/daemon/daemon.js

This improves UX and error reporting in cases like https://github.com/ipfs/ipfs-desktop/issues/2038

fix: static message when ipfs daemon dies on start

---

src/daemon/daemon.js

fix: return error instead of throw

---

README.md

repo.lock issues are frequent, and we don't have an easy place for users to find a solution for this. This PR should help.

docs: Add repo.lock troubleshooting steps to readme

---

package-lock.json
package.json
src/analytics/index.js
src/analytics/keys.js
src/common/logger.js
src/index.js
src/metrics/appStart.js
src/webui/index.js
src/webui/preload.js
tsconfig.json
types/countly-sdk-nodejs.d.ts

This PR adds metrics around app ready, so that the branch `1177-refactor-ctx-speed-improvements` can show us how much it improves load times.
Visually, it's almost instant versus an abrupt error in the first-page-load, and then a painful wait until the ipfsd daemon starts.
`APP_READY` currently shows a load time of 13.10~ seconds with this update, and I'm sure the aforementioned branch only takes 2.
```json
{\"key\":\"APP_READY\",\"count\":1,\"dur\":13.142644000053405,\"timestamp\":1651716859103,\"hour\":19,\"dow\":3}]","app_key":"REDACTED","device_id":"REDACTED","sdk_name":"javascript_native_nodejs","sdk_version":"20.11","timestamp":1651716859307,"hour":19,"dow":3}
```

feat: Add app&webui ready/load metrics

---

src/common/store.js

Closes #1859
This PR removes the hard-coded dht client mode and instead relies on go-ipfs' defaults which test for the node's dialability and if so switch the DHT to server mode automatically.
A migration was added to remove the hard-coded routing configration from the users config.json.

Remove hardcoded DHT client routing

---

DEVELOPER-NOTES.md

Updating QA script to reflect reality about what is important (I've been testing these on every release).

docs: update manual QA script

---

.github/ISSUE_TEMPLATE/bug_report.md
README.md

docs: add network error troubleshoot

---

package.json

This bumps ifps-webui to the latest release: https://github.com/ipfs/ipfs-webui/releases/tag/v2.15.1

feat: ipfs-webui v2.15.1

---

.github/workflows/auto-project.yml

Don't know if you saw this one - there's an action for adding to project which is maintained by GitHub - https://github.com/actions/add-to-project. In general, I think it's a safe default to use GitHub's things when they're good enough. Feel free to close if you want some of those extra features that the other action comes with.
disclaimer: not tested - just wanted to draw your attention to this

chore: use official github action in auto-project

---

assets/locales/en.json
src/daemon/config.js
src/daemon/daemon.js

Closes #2221 by not letting users use IPFS Desktop with a private network IPFS node, as discussed in yesterday's triage meeting. IPFS Desktop is built with public networks in mind.

fix: quit if repository is part of private network

---

src/daemon/config.js
test/e2e/launch.e2e.test.js

Remove patch for go-ipfs < 0.13.
License: MIT

chore(maintenance): remove addedApiPort after go-ipfs 0.13

---

assets/locales/en.json
src/daemon/config.js
src/daemon/consts.js
src/daemon/daemon.js
src/daemon/dialogs.js
src/daemon/index.js
src/daemon/migration-prompt.js

While doing #2225, I noticed there are some few things could be improved:
License: MIT

feat: jsdoc and improvements to daemon logic

---

src/dialogs/errors.js

Sometimes we need to know the user's platform (OS) version and not just which OS it is. This PR adds the [`os.release()`](https://nodejs.org/api/os.html#osrelease) to give us that information. Please note that this releases might not be 1:1 connected with the commercial names of the OSes. For macOS, for example, version 12.5, we get a kernel version of 21.6.0.
The other option, with more information, would be to print [`os.version()`](https://nodejs.org/api/os.html#osversion), which provides even more information:
```node
> os.release()
'21.6.0'
> os.platform()
'darwin'
> os.version()
'Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000'
```
I personally think `os.version()` would be better and more informative, but it is not as succinct. …

feat: include platform version in error report

---

src/daemon/config.js

Fixes #2254 by adding a simple check to make sure `.Swarm.ConnMgr` actually exists in the configuration before changing it.
I thought about adding a test case for this, but then I would also have to add one for all the remaining migrations. However, I think that would almost duplicate the E2E time testing.

fix: ensure .Swarm.ConnMgr exists before accessing

---

src/analytics/index.js
src/common/ipc-main-events.js
src/daemon/index.js
src/i18n.js
src/take-screenshot.js
src/tray.js
src/utils/setup-global-shortcut.js
src/webui/connection-status.js
src/webui/index.js
src/webui/preload.js
src/webui/screenshot.js
test/unit/create-toggler.spec.js

refactor: use ipcMainEvents constant 

---

package-lock.json
package.json

Related https://github.com/ipfs/kubo/issues/9237

chore: bump go-ipfs version to 0.16.0

---

electron-builder.yml

This PR aims to close #2291  by changing implicit `artifactName` to explicit ones in `electron-builder.yml`, setting different ones for `.zip` and `.dmg` mac targets.
We can't remove .zip because of reasons described in https://github.com/ipfs/ipfs-desktop/issues/1922#issuecomment-991352450, but we can rename it to something  other than `-mac`.
```
IPFS-Desktop-0.24.0.dmg
IPFS-Desktop-0.24.0.dmg.blockmap
IPFS-Desktop-0.24.0-mac.zip
IPFS.Desktop-0.24.0-mac.zip.blockmap
```
```
ipfs-desktop-0.24.0-mac.dmg
ipfs-desktop-0.24.0-mac.dmg.blockmap
ipfs-desktop-0.24.0-squirrel.zip
ipfs-desktop-0.24.0-squirrel.zip.blockmap
```

fix: adjust mac and dmg artifactName

---

package.json

https://github.com/ipfs/ipfs-webui/releases/tag/v2.20.0
Blocked By: https://github.com/protocol/bifrost-infra/issues/2186

feat: Updating ipfs-webui CID to v2.20.0

---

package.json

> This is ipfs-desktop version of https://github.com/ipfs/kubo/pull/9490
Ref. https://github.com/ipfs/ipfs-webui/releases/tag/v2.21.0
We need this fix before Kubo 0.18-0-rc1 ships  (https://github.com/ipfs/kubo/issues/9417), otherwise Peers screen in IPFS Desktop will fail to show  `/quic-v1` peers that have it enabled  (https://github.com/ipfs/kubo/issues/9410).

fix: support /quic-v1 on Peers page

---

src/add-to-ipfs.js
test/unit/add-to-ipfs.spec.js

IPFS desktop currently defaults to using CIDv0 when importing files and adding them to IPFS. This PR changes the default to use CIDv1. 
This should solve https://github.com/ipfs/ipfs-desktop/issues/2361 and make sure IPFS Desktop is using the most up-to-date CID standard.

Use CIDv1 by default

---

src/tray.js

Fixes #2424 
https://user-images.githubusercontent.com/53405160/235522592-00b660d8-0a4b-4ca7-b7d3-8ae98fc3c418.mp4

fix: Fix incorrect link for Kubo version in tray icon

---

package.json

Uses the [webui@4.0.0](https://github.com/ipfs/ipfs-webui/releases/tag/v4.0.0) with ipld-explorer-components update
---
Notes: tested locally with `npm run start` and `CSC_IDENTITY_AUTO_DISCOVERY=false npm run package`

feat: webui@4.0.0

---

src/context.js
src/i18n.js
src/tray.js

The [lazy-loading ctx feature](https://github.com/ipfs/ipfs-desktop/pull/2378) didn't catch that i18n wasn't being init before tray translations were attempted.
That means the tray-menu-item translations were occurring prior to loading the
translation files, which defaults the translated result to the given key.
This PR resolves that problem.
fixes https://github.com/ipfs/ipfs-desktop/issues/2595

fix: tray translation waits for i18n init

---

src/common/ipc-main-events.js
src/context.js
src/i18n.js
src/tray.js

fixes #2599
There was a previous bug with the menu that we fixed with https://github.com/ipfs/ipfs-desktop/pull/2594 but that resulted in some properties not being updated because we were updating a new `Menu.buildFromTemplate` object, and not calling
`tray.setContextMenu(menu)` again.
This fix reverts some of those changes, but still ensures that https://github.com/ipfs/ipfs-desktop/issues/2591 is not occurring.
This change also fixes an issue, probably introduced with the lazy ctx refactor, that prevented the systray menu items from being re-translated when the language was updated.

fix: ensure menu items update properly

---

DEVELOPER-NOTES.md
README.md
src/argv-files-handler.js
src/auto-updater/index.js
types/countly-sdk-nodejs.d.ts

chore: typo fixes

---

README.md

Adds one new main section, with two subsections, to the https://github.com/ipfs/ipfs-desktop#faq--troubleshooting section of the README:
1. Error: Initializing daemon...
* Error: Your programs version (N) is lower than your repos (N+x).
* Found outdated fs-repo, migrations need to be run. - Error fetching: context deadline exceeded
Hopefully these instructions will help users unblock themselves, as well as give us give us a standard place to send users who run into these issues.

docs(readme): add repo migration FAQ sections

---

src/i18n.js

i18next has some auto-magical loading of translation files that kicks
off loading multiple languages (e.g. 'en', 'en-US', 'en-UK', etc.) but
we don't have all of those files for IPFS-Desktop. i18next.init
will fire an error if any of those files fail to load, even if one
succeeds.
This fix ensures that `i18n.initDone` is set on context even if we see
an error.
fixes #2627

fix: i18n init done fires even with lang load error

---

package.json

patch release that removes unnecessary requests to countly.ipfs.io which is no longer online 
closes #2743 
https://github.com/ipfs/ipfs-webui/releases/tag/v4.2.1

chore: webui v4.2.1

---

README.md

This PR surfaces information about download pings related to autoupdate mechanism used by existing users.
This allows us to show current reach of IPFS Desktop when discussing funding with third-parties.

docs(readme): additional download metrics

---

src/dialogs/errors.js

We have the same errors reported over and over again and there is FAQ for them.
This PR ensures these errors are not reported anymore, but the user is routed to relevant FAQ entry instead, to self-service by following instructions from FAQ.
Closes #2744
Closes #2787
Closes #2807
Closes #2301
Closes #2754
Closes #2765
Closes #2768
Closes #2769
Closes #2791
Closes #2824

docs: link to faq on known error

---

.gitignore
electron-builder.yml
package-lock.json
package.json
patches/multiaddr+10.0.1.patch
src/protocol-handlers.js
src/webui/open-external.js

feat: electron 31

---

package.json

updates ipfs-webui to use the latest version. Some major dep overhauls done thanks to ipld-explorer-components update & removal of `bundlesize` dev-dep
Related: 
* https://github.com/ipfs/ipfs-webui/releases/tag/v4.4.0
* https://github.com/ipfs/ipld-explorer-components/compare/v7.0.3...v8.1.0

feat: ipfs-webui v4.4.0

---

package.json

This reverts commit 77765e28939895a99455a3be2df2b4b088504a3c.
Switching back to ipfs-webui v4.3.3 due to the problem described in https://github.com/ipfs/ipfs-desktop/pull/2887#issuecomment-2489619962

fix(explore): switch back to ipfs-webui v4.3.3

---

README.md
package-lock.json
package.json

This PR is downgrading electron to 35.x until it is "safe" to use GTK4 as the new default.
It also adds entry to FAQ in case someone updates it before it gets fixed, and/or error hits users in the future.
Closes #2952
This feels safer than hardcoding
```js
app.commandLine.appendSwitch('gtk-version', '3')
```
in our code, or asking people to "self-fix" broken app by passing `--gtk-version`.
Both are very bad UX and brittle long term.

fix(linux): electron 35 to fix GTK error

---

README.md

**Description**
This PR fixes the broken **build process** link in the README.md.
Removed unnecessary backticks around .github/workflows/ci.yml
Updated the link to correctly point to the CI workflow file
Fixes: #2985

chore(readme): fix correct broken CI link
